const SECRET='kuber';
const lock=document.getElementById('lock'),app=document.getElementById('app'),pass=document.getElementById('pass'),unlock=document.getElementById('unlock'),wrong=document.getElementById('wrong');
function openSite(){lock.classList.add('hidden');app.classList.remove('hidden');sessionStorage.setItem('kg_open','1');}
if(sessionStorage.getItem('kg_open')==='1')openSite();
unlock.onclick=()=>{if(pass.value.trim().toLowerCase()===SECRET)openSite();else{wrong.textContent='Not that one ♥ Try again.';pass.value='';pass.focus()}};pass.addEventListener('keydown',e=>{if(e.key==='Enter')unlock.click()});
const gallery=document.getElementById('gallery'),files=document.getElementById('files'),clear=document.getElementById('clear');let photos=JSON.parse(localStorage.getItem('kg_gallery')||'[]');
function save(){localStorage.setItem('kg_gallery',JSON.stringify(photos))}function render(){gallery.innerHTML='';if(!photos.length){gallery.innerHTML='<div class="empty"><b>♡</b><h3>Your memory vault is waiting.</h3><p>Add your favourite photos above.</p></div>';return}photos.forEach((src,i)=>{const d=document.createElement('div');d.className='photo';d.innerHTML=`<img src="${src}" alt="Memory"><button class="remove" aria-label="remove">×</button>`;d.querySelector('button').onclick=()=>{photos.splice(i,1);save();render()};gallery.appendChild(d)})}files.onchange=()=>{[...files.files].filter(x=>x.type.startsWith('image/')).forEach(file=>{const r=new FileReader();r.onload=()=>{photos.push(r.result);save();render();toast('Photo added ♥')};r.readAsDataURL(file)});files.value=''};clear.onclick=()=>{if(confirm('Clear all uploaded memories from this browser?')){photos=[];save();render();toast('Memory vault cleared')}};render();
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
document.getElementById('surprise').onclick=()=>{const a=['System update: Kuber is still your favourite human ♥','Warning: excessive cuteness detected.','Forever mode: ENABLED ♥','New memory unlocked ✦','Error 404: someone still cannot stop smiling.'];toast(a[Math.floor(Math.random()*a.length)]);for(let i=0;i<18;i++){const h=document.createElement('div');h.className='float';h.textContent=Math.random()>.15?'♥':'✦';h.style.left=Math.random()*100+'%';h.style.fontSize=12+Math.random()*20+'px';h.style.animationDuration=3+Math.random()*4+'s';document.body.appendChild(h);setTimeout(()=>h.remove(),8000)}};
setInterval(()=>{if(app.classList.contains('hidden'))return;const h=document.createElement('div');h.className='float';h.textContent='♥';h.style.left=Math.random()*100+'%';h.style.fontSize=10+Math.random()*15+'px';h.style.animationDuration=8+Math.random()*7+'s';document.body.appendChild(h);setTimeout(()=>h.remove(),16000)},1100);
let playing=false;document.getElementById('music').onclick=()=>{playing=!playing;toast(playing?'Music button is ready — add your own audio file if you want ♫':'Music paused');};
